df_site/df_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('model_a.urls')),
    path('model_a/', include('model_a.urls')),
    path('admin/', admin.site.urls),
]

df_site/model_a/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from . import backtest_views

app_name = 'model_a'
urlpatterns = [
    path('', views.index_view, name='index'),

    # predict
    path('login', views.login_view, name='view_login'),
    path('predict', views.predict_view, name='view_predict'),
    path('api/target_portfolio', views.target_portfolio_view, name='api_target_portfolio'),

    # backtest
    path('backtest', backtest_views.backtest_view, name='view_backtest'),
    path('api/backtest_returns', backtest_views.returns_view, name='api_backtest_returns'),
    path('api/backtest_weights', backtest_views.weights_view, name='api_backtest_weights'),
    path('api/backtest_revenue_rank', backtest_views.revenue_rank_view, name='api_backtest_revenue_rank'),
    path('api/backtest_price_volume', backtest_views.price_volume_view, name='api_backtest_price_volume'),
]

df_site/model_a/models.py
from django.db import models

# Create your models here.

df_site/model_a/views.py
import os
import json
import io
import pandas as pd

from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login

import common.exception as exception
from dl_models.model_factory import ModelFactory


def code_to_string(code):
  if isinstance(code, int):
    return '{:06d}'.format(code)
  return code


def index_view(request):
  print('=====================')
  print('request', request)
  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse('model_a:view_login'))

  return render(
      request, 'model_a/index.html',
      {'models': ModelFactory.get_models()})


def predict_view(request):
  print('=====================')
  print('request', request)
  if not request.user.is_authenticated:
    return HttpResponseRedirect(reverse('model_a:view_login'))

  if request.method != 'GET':
    return HttpResponseRedirect(reverse('model_a:index'))

  print("GET!!")
  return render(
      request, 'model_a/predict.html',
      {'models': ModelFactory.get_models()})


def login_view(request):
  print('=====================')
  print('[login]:', request)
  if request.method == 'GET':
    return render(request, 'model_a/login.html', {'model_names': ModelFactory.get_names()})

  print('=====================')
  print('POST items')
  for key, value in request.POST.items():
    print(key, value)

  username = request.POST['inputID']
  password = request.POST['inputPassword']
  user = authenticate(request, username=username, password=password)
  if user is not None:
    login(request, user)
    return HttpResponseRedirect(reverse('model_a:index'))

  # Return an 'invalid login' error
  # message.

  return HttpResponseRedirect(reverse('model_a:view_login'))


def compute_portions(close_prices, volumes):
  holdings = [p * v for p, v in zip(close_prices, volumes)]
  total_holding = sum(holdings)
  return [h / total_holding for h in holdings]


def compute_volumes(close_prices, target_portions, total_capital):
  volumes = [int(portion * total_capital) // price
             for price, portion in zip(close_prices, target_portions)]
  return volumes


def target_portfolio_view(request):
  print('current directory', os.getcwd())
  if not request.user.is_authenticated:
    return HttpResponse(json.dumps({"error": "not logged in"}))

  if request.method != 'POST':
    return HttpResponse(json.dumps({"error": "invalid method"}))

  print('=====================')
  print('POST items')
  for key, value in request.POST.items():
    print(key, value)

  try:
    csv_file = request.FILES['inputCsv']
    if not csv_file.name.endswith('.csv'):
      messages.error(request, 'File is not CSV type')
      print("File is not CSV type!!!")
      return HttpResponse(json.dumps({'error': 'File is not CSV type'}))

    # TODO: check file size
    file_data = csv_file.read()
    bytes_io = io.BytesIO(file_data)
    df = pd.read_csv(bytes_io, encoding='CP949')

    max_ticker_counts = int(request.POST.get('maxCounts', '30'))
    model_name = request.POST.get('selectModel', '')
    total_capital = int(request.POST.get('totalCapital', '1000000000').replace(',', ''))
    print('view:max_ticker_counts', max_ticker_counts)
    print('view:Model Name:', model_name)
    print('view:total_capital', total_capital)
    model = ModelFactory.get_portfolio_builder(model_name)

    target_date = request.POST['targetDate']
    input_volumes = [(code_to_string(row['code']), row['volume'], row['name'])
                     for _, row in df.iterrows()]
    universe = [v[0] for v in input_volumes]

    price_dicts = model.get_price_inputs_np(universe, target_date)
    close_prices = [int(v[-1][1]) for v in price_dicts['inputs_raw']]
    del price_dicts['inputs_raw']
    current_volumes = [v[1] for v in input_volumes]
    current_portions = compute_portions(close_prices, current_volumes)

    target_portions = model.inference(universe,
                                      current_portions,
                                      target_date,
                                      price_dicts,
                                      max_ticker_counts=max_ticker_counts)
    target_portions = [v[1] for v in target_portions]
    target_volumes = compute_volumes(close_prices, target_portions, total_capital)

    rows = []
    for cur, close, portion, volume, target_portion, target_volume, in zip(input_volumes,
                                                                           close_prices,
                                                                           current_portions,
                                                                           current_volumes,
                                                                           target_portions,
                                                                           target_volumes):
      rows.append({'code': cur[0],
                   'name': cur[2],
                   'close': close,
                   'current_portion': portion,
                   'current_volume': volume,
                   'target_portion': target_portion,
                   'target_volume': target_volume,
                   })

    print("Response!!!")
    return HttpResponse(json.dumps({'rows': rows}))

  except exception.BaseError as e:
    print('BaseError', e.message)
    messages.error(request, 'Exception:' + e.message)
    return HttpResponse(json.dumps({'error': e.message}))

  except Exception as e:
    print('Exception', e)
    messages.error(request, 'Unable to upload file. ' + repr(e))
    return HttpResponse(json.dumps({'error': repr(e)}))

df_site/model_a/templates/model_a/backtest.html
{% extends "model_a/base.html" %}
{% load static %}

{% block title %}BackTest{% endblock %}

{% block content %}
<main role="main">
  <br/>
  <div class="container row">
    <br/>
    <div class="input-field col s4">
      <select id="select-model" onchange="load_data();" size="4">
        <option value="" disabed selected>Choose model</option>
        {% for model in models %}
				<option value={{ model.name }} {{ model.selected }}>{{ model.display }}</option>
        {% endfor %}
      </select>
      <label>Select Model</label>
    </div>
    <div class="input-field col s4">
      <input id='start-date' type="text" class="datepicker" />
      <label>Select start date</label>
    </div>
    <div class="input-field col s4">
      <input id='end-date' type="text" class="datepicker" />
      <label>Select end date</label>
    </div>
  </div>
  <div class="container">
    <div>
      <ul class="collapsible popout">
        <li id='li-returns' class="active">
          <div class="collapsible-header grey lighten-4"><i class='material-icons'>show_chart</i>수익률</div>
					<div class="collapsible-body"><div id="graph-returns"></div></div>
        </li>
        <li id='li-weights'>
          <div class="collapsible-header grey lighten-4"><i class='material-icons'>pie_chart</i>보유비중</div>
					<div class="collapsible-body"><div id="graph-weights"></div></div>
        </li>
        <li id='li-revenue-rank'>
          <div class="collapsible-header grey lighten-4"><i class='material-icons'>monetization_on</i>실현수익(상위10/하위10)</div>
					<div class="collapsible-body"><div id="graph-revenue-rank"></div></div>
        </li>
        <li id='li-single-stock'>
          <div class="collapsible-header grey lighten-4"><i class='material-icons'>multiline_chart</i>보유량/종가/실현수익</div>
					<div class="collapsible-body"><div id="graph-single-stock"></div></div>
        </li>
      </ul>
    </div>
  </div>
</main>
{% endblock %}

{% block script %}

<script>

var graphReturns = document.getElementById('graph-returns');
var graphWeights = document.getElementById('graph-weights');
var graphRevenueRank = document.getElementById('graph-revenue-rank');
var graphSingleStock = document.getElementById('graph-single-stock');

function load_weights(params, selectedDate) {
	// var params = { "model": model, "selected_date": selectedDate }
	params.selected_date = selectedDate.replace(/-/gi, '/')
	$.ajax({
    url: "{% url 'model_a:api_backtest_weights' %}",
		type: 'GET',
		data: params,
		success: function (res) {
			var res = JSON.parse(res);
			var texts = res.weights.map(function (w, i) {
				if (w > 0.02)
					return (w * 100).toFixed(2) + '%, ' + res.universe[i]
				return ''
			});

			var trace = { labels: res.universe,
										values: res.weights,
										type: 'pie',
										text: texts,
										textinfo: 'text',
										hoverinfo: 'label+percent+name'};
			var data = [trace];

			var layout = {
				margin: { l: 40, r: 40, b: 20, t: 60 },
				title: params.selected_date
			};

			$('.collapsible').collapsible('open', 1)
			Plotly.newPlot(graphWeights, data, layout);
		},
		error: function (jqXHR, textStatus, errorThrown) {
			console.log("load_weights: FAIL. " + textStatus + " : " + errorThrown);
		}
	});
}

function load_price_volume(params, selectedTicker) {
	params.ticker = selectedTicker.slice(0, 6)

	$.ajax({
    url: "{% url 'model_a:api_backtest_price_volume' %}",
		type: 'GET',
		data: params,
		success: function (res) {
			var res = JSON.parse(res);
			res.dates = res.dates.map(function (currentValue) { return new Date(currentValue); })

			// graph data
			var trace1 = { x: res.dates, y: res.holding, type: 'scatter', name: '보유수량' }
			var trace2 = { x: res.dates, y: res.weights, type: 'scatter', name: '보유비중', yaxis: 'y2' }
			var trace3 = { x: res.dates, y: res.close, type: 'scatter', name: '종가', yaxis: 'y3' }
			var trace4 = { x: res.dates, y: res.accumulated_revenue, type: 'scatter', name: '실현수익', yaxis: 'y4' }
			var data = [trace1, trace2, trace3, trace4];

			// graph layout
			var layout = {
				title: selectedTicker,
				autosize: true,
				height: 240,
				margin: { l: 40, r: 40, b: 20, t: 40 },
				xaxis: { domain: [0.075, 0.9] },
				yaxis1: { title: '보유수량(주)' },
				yaxis2: { title: '보유비중', overlaying: 'y', side: 'left', anchor: 'free', position: 0.0 },
				yaxis3: { title: '종가(원)', overlaying: 'y', side: 'right' },
				yaxis4: { title: '실현수익(원)', overlaying: 'y', anchor: 'free', side: 'right', position: 0.97 },
			};

			// plot graph
			$('.collapsible').collapsible('open', 3)
			Plotly.newPlot(graphSingleStock, data, layout);
		},
		error: function (jqXHR, textStatus, errorThrown) {
			console.log(textStatus + " : " + errorThrown);
		}
	});
}

function load_revenue_rank(params) {
	$.ajax({
    url: "{% url 'model_a:api_backtest_revenue_rank' %}",
		type: 'GET',
		data: params,
		success: function (res) {
			var res = JSON.parse(res);

			// graph data
      var colors = Array(20).fill('rgb(222,45,38)', 0, 10).fill('rgb(45,38,222)', 10, 20)
			var trace = { x: res.labels, y: res.revenues, type: 'bar', marker: { color: colors } }
			var data = [trace];

			// graph layout
			var layout = {
				autosize: true,
				height: 240,
				margin: { l: 40, r: 120, b: 120, t: 20 }
			};

			// plot graph
			Plotly.newPlot(graphRevenueRank, data, layout);
			graphRevenueRank.on('plotly_click', function (data) {
				load_price_volume(params, data.points[0].x);
			});
		},
		error: function (jqXHR, textStatus, errorThrown) {
			console.log(textStatus + " : " + errorThrown);
		}
	});
}

function load_returns(params) {
	// load data from server
	$.ajax({
    url: "{% url 'model_a:api_backtest_returns' %}",
		type: 'GET',
		data: params,
		success: function (res) {
			var res = JSON.parse(res);

			res.dates = res.dates.map(function (currentValue) { return new Date(currentValue); })

			// graph data
			var trace1 = { x: res.dates, y: res.returns, type: 'scatter', name: 'Back Test' }
			var trace2 = { x: res.dates, y: res.returns_bnh, type: 'scatter', name: 'Buy & Hold' }
			var trace3 = { x: res.dates, y: res.returns_kospi, type: 'scatter', name: 'KOSPI' }
			var trace4 = { x: res.dates, y: res.volumes, type: 'bar', name: '거래량', xaxis: 'x2', yaxis: 'y2' }
			var trace5 = { x: res.dates, y: res.max_weights, type: 'scatter', name: '단일종목 최대보유비중', xaxis: 'x2', yaxis: 'y2' }
			var data = [trace1, trace2, trace3, trace4, trace5];

			// graph layout
			var layout = {
				title: '기간: ' + params.start_date + ' ~ ' + params.end_date,
				autosize: true,
				height: 360,
				margin: { l: 40, r: 40, b: 20, t: 40 },
				yaxis: {domain: [0.366, 1.0]},
				yaxis2: {overlaying: 'y2', side: 'left', domain: [0, 0.266]},
				xaxis2: {anchor: 'y2'},
				legend: { orientation: 'h' }
			};

			// plot graph
			Plotly.newPlot(graphReturns, data, layout);
			graphReturns.on('plotly_click', function (data) {
				load_weights(params, data.points[0].x);
			});
		},
		error: function (jqXHR, textStatus, errorThrown) {
			console.log(textStatus + " : " + errorThrown);
		}
	});
}

function load_data() {
	var model = $("#select-model option:selected").val();
	var startDate = $("#start-date").val();
	var endDate = $("#end-date").val();

	// check input
	if (model === "" || startDate === "" || endDate === "")
		return

	// TODO: date range check
	if (new Date(startDate) >= new Date(endDate)) {
		alert("잘못된 날짜 범위입니다.")
		return
	}

	var params = { "model": model, "start_date": startDate, "end_date": endDate };

	load_returns(params);
	load_revenue_rank(params);
}

window.onresize = function () {
	Plotly.Plots.resize(graphReturns);
};

$(document).ready(function() {
	activateMenu("navBacktest")

  // select box
  $('select').formSelect();

  // date picker
  var options = {
		format: 'yyyy/mm/dd',
		autoClose: true,
		setDefaultDate: true,
		parse: function (s) { return new Date(s); },
		onSelect: function (v) { console.log(v); },
		onClose: function () { load_data(); },
		yearRange: [2012, 2019],
		minDate: new Date(2012,0,1),
		maxDate: new Date(2019,0,1)}

  // $('.datepicker').datepicker(options);

	options.defaultDate = options.minDate
  $('#start-date').datepicker(options)

	options.defaultDate = options.maxDate
  $('#end-date').datepicker(options)

  // collapsibles
	$('.collapsible').collapsible({
		accordion: false,
		onOpenEnd: function (l) {
			var graphDict = {}
			graphDict['li-returns'] = graphReturns;
			graphDict['li-weights'] = graphWeights;
			graphDict['li-revenue-rank'] = graphRevenueRank;
			graphDict['li-single-stock'] = graphSingleStock;
			Plotly.Plots.resize(graphDict[l.id]);
		}
	});

	// 
	load_data()
});

document.addEventListener('DOMContentLoaded', function() {
  var options = {
		format: 'yyyy/mm/dd',
		autoClose: true,
		setDefaultDate: true,
		parse: function (s) { return new Date(s); },
		onSelect: function (v) { console.log(v); },
		onClose: function () { load_data(); },
		yearRange: [2012, 2019],
		minDate: new Date(2012,0,1),
		maxDate: new Date(2019,0,1)}

  var elems = document.querySelectorAll('.datepicker');
  var instances = M.Datepicker.init(elems, options)
});

</script>

{% endblock %}

df_site/model_a/templates/model_a/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta char="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <link rel="stylesheet" href="{% static 'model_a/css/theme.default.css' %}">
  <link rel="stylesheet" href="{% static 'model_a/css/materialize.css' %}">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.1/js/materialize.min.js"></script>
  <script src="{% static 'model_a/js/jquery.tablesorter.js' %}"></script>
  <script src="{% static 'model_a/js/jquery.tablesorter.widgets.js' %}"></script>
  <script src="{% static 'model_a/js/table2csv.js' %}"></script>
  <!--script src="{% static 'model_a/js/bootstrap-datepicker.min.js' %}"></script-->
  <script src="{% static 'model_a/js/plotly-latest.min.js' %}"></script>

  <!-- Icon -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="icon" href="{% static 'model_a/icon/favicon.ico' %}">

  <title>{% block title %}Home{% endblock %}</title>
</head>

<body>

<nav class="blue-grey darken-3">
  <div class="nav-wrapper container">
    <a href="#" class="brand-logo">A.I. PLUS Lab</a>
    <ul class="right hide-on-med-and-down">
      <li class="nav-item" id="navIndex">
        <a class="nav-link" href="{% url 'model_a:index' %}">Home</a>
      </li>
      <li class="nav-item" id="navPredict">
        <a class="nav-link" href="{% url 'model_a:view_predict' %}">Model A</a>
      </li>
      <li class="nav-item" id="navBacktest">
        <a class="nav-link" href="{% url 'model_a:view_backtest' %}">Backtest</a>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  {% block content %}{% endblock %}
</div>

</body>

<script type="text/javascript">
function activateMenu(id) {
  var element, name, arr;
  element = document.getElementById(id);
  name = "active";
  arr = element.className.split(" ");
  if (arr.indexOf(name) == -1) {
    element.className += " " + name;
  }
}
</script>

{% block script %}{% endblock %}

df_site/model_a/templates/model_a/index.html
{% extends "model_a/base.html" %}

{% block title %}Model A{% endblock %}

{% block content %}
<main role="main">
</main>
{% endblock %}

{% block script %}

<script type="text/javascript">
$(document).ready(function() {
	activateMenu("navIndex")
});
  
</script>

{% endblock %}

df_site/model_a/templates/model_a/predict.html
{% extends "model_a/base.html" %}
{% load static %}

{% block title %}Model A{% endblock %}

{% block content %}
<main role="main">

<div id="modalDescription" class="modal">
  <div class="modal-content">
    <h5 class="modal-title" id="exampleModalCenterTitle">모델 설명</h5>
    <table class="table">
      <tr><th scop="row">종목</th><td>[<a href="#" target="_blank" id="linkUniverse">download</a>]</td></tr>
      <tr><th scop="row">백테스트</th><td>[<a href="#" target="_blank" id="linkBacktest">link</a>]</td></tr>
      <tr><th scop="row">학습기간</th><td id="tdTrainingDates"></td></tr>
      <tr><th scop="row">리밸런싱주기</th><td id="tdRebalancing"></td></tr>
      <tr><th scop="row">최대보유종목수</th><td id="tdMaxAssets"></td></tr>
      <tr><th scop="row">가능종목조건</th><td id="tdConditions"></td></tr>
    </table>
  </div>
</div>

<div style="display: none; visible: hidden">
  {% for model in models %}
  <span style="display: none;" id="desc_{{ model.name }}">{{ model.description }}</span>
  {% endfor %}
</div>

<br />
<div class="container">
  <form method="POST" id="formUpload" enctype="multipart/form-data" novalidate> 
    {% csrf_token %}
    <div class="row">
      <div class="input-field col s10">
        <select id="selectModel" required="True">
          <option value="" disabled selected>Select Model</option>
          {% for model in models %}
          <option value={{ model.name }}>{{ model.display }}</option>
          {% endfor %}
        </select>
        <label>Select Model</label>
      </div>
      <div class="input-field col s2">
        <a class="waves-effect waves-light btn-small" onclick="showModelDescription()">모델설명</a>
      </div>
    </div>
    <div class="row">
      <div class="file-field input-field col s12">
        <div class="waves-effect btn-small">
          <span>Select CSV</span>
          <input type="file" id="inputCsv" name="inputCsv" required="True">
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s4">
        <input value="1,000,000,000" id="totalCapital" type="text" class="validate">
        <label for="totalCapital">Total amount of capital</label>
      </div>
      <div class="input-field col s4">
        <input value="30" id="maxCounts" type="text" class="validate">
        <label for="maxCounts">Max holdings</label>
      </div>
      <div class="input-field col s4">
        <input id='dateTarget' type="text" class="datepicker" />
        <label>Select Date</label>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <button class="btn-small waves-effect waves-light" type="submit" name="action">Submit</button>
        <a class="wave-effect btn-small" id="btnExportCsv">Export CSV</a>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <table class="tablesorter" id="tblTargetPortfolio">
          <thead class="thead-dark">
            <tr>
              <th scope="col">code</th>
              <th scope="col">name</th>
              <th scope="col">close</th>
              <th scope="col">current volume</th>
              <th scope="col">current portion</th>
              <th scope="col">target volume</th>
              <th scope="col">target portion</th>
              <th scope="col">difference(volume)</th>
              <th scope="col">difference(portion)</th>
            </tr>
          </thead>
          <div data-spy="scroll" data-offset="0">
          <tbody data-spy="scroll">
          </tbody>
        </table>
        <div id="divProgress" class="center-align" style="display: none;">
          <img src="{% static 'model_a/icon/spinner.gif' %}" class="mx-auto d-block" />
        </div>
      </div>
    </div>
  </form>
</div>

<div id="modalError" class="modal">
  <div class="modal-content">
    <h5>Error:</h5>
    <h6><div id="divError"></div><h6>
  </div>
</div>

</main>
{% endblock %}

{% block script %}

<script type="text/javascript">
$(document).ready(function() {
  activateMenu("navPredict")

  $('select').formSelect();
  $('.modal').modal();

  // date picker
  var options = {
    format: 'yyyy-mm-dd',
    autoClose: true,
    setDefaultDate: true,
    defaultDate: new Date(),
    parse: function (s) { return new Date(s); }
  }

  $('.datepicker').datepicker(options);

  $('table').tablesorter({
    widgets: ['zebra', 'columns'],
    sortReset: true,
    sortRestart: true
  });

  $("#btnExportCsv").click(function(){
    $("#tblTargetPortfolio").table2csv('output', {appendTo: '#out'});
    $("#tblTargetPortfolio").table2csv('download', {filename: 'target_portfolio.csv'});
  })

  $('#divDateTarget').datepicker({
        autoclose: true,
        format: 'yyyy-mm-dd'
  });

  $('#divProgress').hide()
});


// function onSubmit(data) {
$('#formUpload').submit(function (event) {
  event.preventDefault();

  var model = $("#selectModel option:selected").val();
  if (model == "")
    return

  console.log('submit')
  var form = $('form')[0];
  var form_data = new FormData(form);
  form_data.append('selectModel', $("#selectModel option:selected").val());
  form_data.append('totalCapital', $("#totalCapital").val());
  form_data.append('targetDate', $("#dateTarget").val());
  form_data.append('maxCounts', $("#maxCounts").val());

  // clear table
  $("#tblTargetPortfolio > tbody:last").children().remove();
  var resort = true;
  $('table').trigger("update", [resort]);

  $('#divProgress').show()

  $.ajax({
    url: "{% url 'model_a:api_target_portfolio' %}",
    type: "POST",
    data: form_data,
    processData: false,
    contentType: false,
    success: function (data, textStatus, jqXHR) {
      $('#divProgress').hide()
      try {
        var jsonData = JSON.parse(data);
        drawTable(jsonData.rows);
      }
      catch (e) {
        var error = JSON.parse(data)
        console.log(error)
        $("#divError").text(error.error)
        $("#modalError").modal("open")
        // alert(error.error);
      }
    }
  });
})


function drawTable(data) {
  $("#tblTargetPortfolio > tbody:last").children().remove();
  for (var i = 0; i < data.length; i++) {
    drawRow(data[i]);
  }

  var resort = true;
  $('table').trigger("update", [resort]);
}


function drawRow(rowData) {
  var row = $("<tr/>")
  $("#tblTargetPortfolio").append(row);
  row.append($("<td>" + rowData.code + "</td>"))
  row.append($("<td>" + rowData.name + "</td>"))
  row.append($("<td>" + rowData.close + "</td>"))
  row.append($("<td>" + rowData.current_volume + "</td>"))
  row.append($("<td>" + rowData.current_portion.toFixed(4) + "</td>"))
  row.append($("<td>" + rowData.target_volume + "</td>"))
  row.append($("<td>" + rowData.target_portion.toFixed(4) + "</td>"))
  row.append($("<td>" + (rowData.target_volume - rowData.current_volume) + "</td>"))
  row.append($("<td>" + (rowData.target_portion - rowData.current_portion).toFixed(4) + "</td>"))
}


function exportTableToCSV() {
  function f($table, filename) {
    var $rows = $table.find('tr')
    var colDelim = '","'
    var rowDelim = '"\r\n"'
    var csv = '"' + $rows.map(function (i, row) {
      var $row = $(row)
      var $cols = $row.find('th,td')
  
      return $cols.map(function (i, col) {
        var $col = $(col)
        var text = $col.text();
        return text.replace(/"/g, '""');
      }).get().join(colDelim);
    }).get().join(rowDelim) + '"';
  
    if (window.Blob && window.URL) {
      var blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
      var csvUrl = URL.createObjectURL(blob);

      var downloadLink = document.createElement("a");
      downloadLink.href = csvUrl
      downloadLink.download = filename

      document.body.appendChild(downloadLink)
      downloadLink.click();
      document.body.removeChild(downloadLink)
    } else {
      var csvData = 'data:application/csv;charset=utf-8,' + encodeURIComponent(csv);

      var downloadLink = document.createElement("a");
      downloadLink.href = csvUrl
      downloadLink.download = filename

      document.body.appendChild(downloadLink)
      downloadLink.click();
      document.body.removeChild(downloadLink)
    }
  }

  f($('#tblTargetPortfolio'), 'export.csv');
}


function showModelDescription() {
  var model = $("#selectModel option:selected").val();
  if (model == "") {
    alert("모델을 선택하세요.")
    return
  }

  var desc_elem = $('#desc_ver_0_1')
  var desc = desc_elem.text()
  console.log(desc)

  var desc_elem = $('#desc_' + model)
  var desc = desc_elem.text()
  console.log(desc)

  var data = JSON.parse(desc)
  //'{"universe": "https://www.naver.com", "backtest": "https://www.google.co.kr", "description": "주1회 리밸런싱. <br/> 최대 30종목 보유."}')
  console.log(data)

  var linkUniverse = document.createElement('a')

  $("#linkUniverse").attr("href", data.universe)
  $("#linkBacktest").attr("href", data.backtest)
  $("#tdTrainingDates").text(data.training_dates)
  $("#tdRebalancing").text(data.rebalancing)
  $("#tdMaxAssets").text(data.max_assets)
  $("#tdConditions").text(data.conditions)

  $("#modalDescription").modal("open")
}
  
</script>
{% endblock %}